main:
  params: [ event ]
  steps:
    - launchRawToDomainFunction:
        call: http.post
        args:
          url: https://europe-west1-gb-poc-373711.cloudfunctions.net/qatar-world-cup-stats-raw-to-domain-data-gcs-wf
          auth:
            type: OIDC
        result: launchRawToDomainFunction
    - launchAddFifaRankingToTeamStatsFunction:
        call: http.post
        args:
          url: https://europe-west1-gb-poc-373711.cloudfunctions.net/qatar-world-cup-add-fifa-ranking-to-stats-domain-bq-wf
          auth:
            type: OIDC
        result: launchAddFifaRankingToTeamStatsFunction
    - launchMoveProcessedFilesToColdBucketFunction:
        call: http.post
        args:
          url: https://europe-west1-gb-poc-373711.cloudfunctions.net/qatar-world-cup-move-processed-files-to-cold-bucket-wf
          auth:
            type: OIDC
        result: launchMoveProcessedFilesToColdBucketFunction
    - returnResult:
        return: launchMoveProcessedFilesToColdBucketFunction