main:
  params: [ event ]
  steps:
    - launchRawToDomainService:
        call: http.post
        args:
          url: https://qatar-world-cup-stats-raw-to-domain-data-gcs-sv-w-4wtmsxga6q-ew.a.run.app
          auth:
            type: OIDC
        result: launchRawToDomainService
    - launchAddFifaRankingToTeamStatsService:
        call: http.post
        args:
          url: https://qatar-world-cup-add-fifa-ranking-to-stats-domain7-4wtmsxga6q-ew.a.run.app
          auth:
            type: OIDC
        result: launchAddFifaRankingToTeamStatsService
    - launchMoveProcessedFilesToColdBucketService:
        call: http.post
        args:
          url: https://qatar-world-cup-move-processed-files-to-cold-bucw-4wtmsxga6q-ew.a.run.app
          auth:
            type: OIDC
        result: launchMoveProcessedFilesToColdBucketService
    - returnResult:
        return: launchMoveProcessedFilesToColdBucketService