main:
  params: [ event ]
  steps:
    - init:
        assign:
          - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - location_id: "global"
          - location: ${sys.get_env("GOOGLE_CLOUD_LOCATION")}
          - workflow_service_account_name: ${sys.get_env("GOOGLE_CLOUD_SERVICE_ACCOUNT_NAME")}
          - workflow_execution_id: ${sys.get_env("GOOGLE_CLOUD_WORKFLOW_EXECUTION_ID")}
    - launchRawToDomainFunction:
        call: http.get
        args:
          url: https://europe-west1-gb-poc-373711.cloudfunctions.net/qatar-world-cup-stats-raw-to-domain-data-gcs-wf
        result: launchRawToDomainFunction
    - launchAddFifaRankingToTeamStatsFunction:
        call: http.get
        args:
          url: https://europe-west1-gb-poc-373711.cloudfunctions.net/qatar-world-cup-add-fifa-ranking-to-stats-domain-bq-wf
        result: launchAddFifaRankingToTeamStatsFunction
    - launchMoveProcessedFilesToColdBucketFunction:
        call: http.get
        args:
          url: https://europe-west1-gb-poc-373711.cloudfunctions.net/qatar-world-cup-move-processed-files-to-cold-bucket-wf
        result: launchMoveProcessedFilesToColdBucketFunction
    - returnResult:
        return: launchMoveProcessedFilesToColdBucketFunction